import type { Post, TrendingRoute, UnansweredQuestion, TopContributor, CommunityStat, AppNotification } from "@/types";

export const MOCK_POSTS: Post[] = [
  {
    id: "post-pinned-1",
    author: {
      id: "usr-admin",
      name: "KOMYUT Admin",
      username: "komyut_team",
      avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      badge: "Community Guide",
      reputationPoints: 12400,
      verifiedAnswersCount: 450,
    },
    title: "Gabay sa Commuters: Paano Magtanong at Mag-verify ng Routes 2026",
    origin: "Metro Manila Transit Network",
    destination: "General Commuter Guide 2026",
    body: "Paalala sa lahat ng commuters: Magtanong gamit ang malinaw na landmark at oras ng biyahe. Siguraduhing i-upvote ang mga verified at subok na commute guides!",
    region: "Metro Manila",
    transportModes: ["MRT-3", "LRT-1", "LRT-2", "Jeepney", "UV Express", "Bus"],
    answerCount: 18,
    upvoteCount: 142,
    userVoteState: null,
    isBookmarked: true,
    status: "pinned",
    createdAt: "Pinned",
  },
  {
    id: "post-1",
    author: {
      id: "usr-1",
      name: "Carlo Mendoza",
      username: "carlom",
      avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
      badge: "Route Master",
      reputationPoints: 3420,
      verifiedAnswersCount: 89,
    },
    title: "May UV Express ba mula SM North EDSA papuntang BGC High Street?",
    origin: "SM North EDSA Terminal",
    destination: "BGC High Street (7th Ave)",
    body: "First time ko pupunta sa BGC for work tomorrow around 7:30 AM. May UV Express ba diretso mula SM North terminal, or mas mabilis mag-MRT papuntang Ayala Tapos BGC Bus? Helpful din malaman saan eksakto ang sakayan sa gabi pabalik.",
    region: "Metro Manila",
    transportModes: ["MRT-3", "Bus", "Walk"],
    answerCount: 5,
    upvoteCount: 38,
    bookmarkCount: 12,
    userVoteState: "up",
    isBookmarked: false,
    status: "verified",
    createdAt: "2h ago",
    comments: [
      {
        id: "c-11",
        postId: "post-1",
        author: {
          id: "usr-2",
          name: "Maria Santos",
          username: "mariacommutes",
          avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
          badge: "LRT Veteran",
          reputationPoints: 1890,
          verifiedAnswersCount: 42,
        },
        body: "Mas mabilis mag-MRT mula SM North/North Ave station papuntang Ayala Station (approx 25 mins). Pagbaba ng Ayala, lakad lang papuntang BGC Bus Terminal sa EDSA-McKinley. Sakay ng West Route or Express BGC Bus papuntang 7th Ave (₱15 fare via Beep card).",
        createdAt: "1h ago",
        upvoteCount: 18,
        isVerified: true,
      },
      {
        id: "c-12",
        postId: "post-1",
        author: {
          id: "usr-bgc",
          name: "Ramon Gomez",
          username: "ramon_g",
          avatarUrl: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&auto=format&fit=crop&q=80",
          badge: "BGC Commuter",
          reputationPoints: 950,
          verifiedAnswersCount: 15,
        },
        body: "May P2P Bus din sa SM North pabalik galing Market! Market! / BGC pag gabi (5 PM to 9 PM). Direct trip yun kaya napakaginhawa!",
        createdAt: "45m ago",
        upvoteCount: 7,
      },
    ],
  },
  {
    id: "post-2",
    author: {
      id: "usr-2",
      name: "Maria Santos",
      username: "mariacommutes",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      badge: "LRT Veteran",
      reputationPoints: 1890,
      verifiedAnswersCount: 42,
    },
    title: "Ano ang updated jeep route mula Cubao papuntang UP Diliman Melchor Hall?",
    origin: "Cubao (Diamond Arcade)",
    destination: "UP Diliman (Melchor Hall)",
    body: "Ano na po ang updated jeep route mula Cubao papuntang UP campus matapos yung bagong rerouting? May Katipunan jeep pa ba sa Ilang-Ilang st., or kailangan sumakay ng Philcoa jeep muna sa Aurora Blvd?",
    region: "Metro Manila",
    transportModes: ["Jeepney", "Walk"],
    answerCount: 4,
    upvoteCount: 29,
    bookmarkCount: 8,
    userVoteState: null,
    isBookmarked: true,
    status: "verified",
    createdAt: "4h ago",
    comments: [
      {
        id: "c-21",
        postId: "post-2",
        author: {
          id: "usr-1",
          name: "Carlo Mendoza",
          username: "carlom",
          avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
          badge: "Route Master",
          reputationPoints: 3420,
          verifiedAnswersCount: 89,
        },
        body: "Sa may Katipunan flyover / Aurora Blvd, may sakayan ng jeep papuntang UP Campus (Katipunan-UP route). Baba ka mismo sa Ylanan or Magsaysay gate, tapos lakad o sakay ng Ikot jeep papuntang Melchor Hall.",
        createdAt: "2h ago",
        upvoteCount: 15,
        isVerified: true,
      },
    ],
  },
  {
    id: "post-3",
    author: {
      id: "usr-3",
      name: "Joshua Dizon",
      username: "josh_d",
      avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
      badge: "Commuter",
      reputationPoints: 450,
      verifiedAnswersCount: 12,
    },
    title: "Saan ang sakayan ng P2P Bus mula Alabang papuntang Robinsons Galleria Ortigas?",
    origin: "Alabang Town Center",
    destination: "Ortigas Center (Robinsons Galleria)",
    body: "Saan po pwedeng sumakay ng P2P bus galing Alabang papuntang Ortigas tuwing rush hour? Magkano po pamasahe at tumatanggap ba sila ng Beep card o cash lang?",
    region: "Metro Manila",
    transportModes: ["Bus", "UV Express"],
    answerCount: 2,
    upvoteCount: 16,
    bookmarkCount: 4,
    userVoteState: null,
    isBookmarked: false,
    status: "answered",
    createdAt: "6h ago",
  },
  {
    id: "post-4",
    author: {
      id: "usr-4",
      name: "Patricia Reyes",
      username: "patty_r",
      avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
      badge: "New Navigator",
      reputationPoints: 120,
      verifiedAnswersCount: 2,
    },
    title: "May UV Express ba mula Fairview Terraces papuntang Eastwood City Libis?",
    origin: "Fairview Terraces",
    destination: "Eastwood City Libis",
    body: "Help guys! May UV Express ba mula Fairview derecho Eastwood Mall o kailangan pa mag-Cubao tapos sakay ng C5 jeep? Magkano tantyang pamasahe kapag gabi (around 10 PM)?",
    region: "Metro Manila",
    transportModes: ["UV Express", "Jeepney"],
    answerCount: 0,
    upvoteCount: 9,
    bookmarkCount: 2,
    userVoteState: null,
    isBookmarked: false,
    status: "unanswered",
    createdAt: "1h ago",
  },
  {
    id: "post-5",
    author: {
      id: "usr-5",
      name: "Kenneth Tan",
      username: "ken_tan",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      badge: "Cebu Transit Specialist",
      reputationPoints: 2150,
      verifiedAnswersCount: 65,
    },
    title: "Paano pumunta mula Mactan Airport papuntang Cebu IT Park sa Lahug?",
    origin: "Mactan Airport (CEB)",
    destination: "Cebu IT Park (Lahug)",
    body: "Paano pumunta mula Mactan Airport papuntang IT Park Lahug gamit ang MyBus o modern jeepney? Magkano fare at gaano katagal ang biyahe pag hapon?",
    region: "Cebu",
    transportModes: ["Bus", "Jeepney"],
    answerCount: 3,
    upvoteCount: 31,
    bookmarkCount: 9,
    userVoteState: null,
    isBookmarked: false,
    status: "answered",
    createdAt: "8h ago",
    comments: [
      {
        id: "c-51",
        postId: "post-5",
        author: {
          id: "usr-5-reply",
          name: "Kenneth Tan",
          username: "ken_tan",
          avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
          badge: "Cebu Specialist",
          reputationPoints: 2150,
          verifiedAnswersCount: 65,
        },
        body: "Sakay ka ng MyBus mula Mactan Airport Terminal 1 o 2 papuntang SM City Cebu (₱50 fare, approx 30-40 mins). Mula SM City Cebu terminal, sakay ng modern jeepney (Cebu CIBUS or Route 04L/04M) papuntang IT Park Lahug (₱15 fare). Total travel time: 50-70 mins.",
        createdAt: "6h ago",
        upvoteCount: 24,
        isVerified: true,
        replies: [
          {
            id: "c-52",
            postId: "post-5",
            parentId: "c-51",
            author: {
              id: "usr-cebu2",
              name: "Dave Ybañez",
              username: "dave_cebu",
              avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80",
              badge: "Commuter",
              reputationPoints: 620,
              verifiedAnswersCount: 8,
            },
            body: "Alternative: kung marami kang bagahe, pwede ring mag-Grab (₱250-₱350) or taxi direct sa IT Park. Pero if budget, solid yung MyBus route ni Kenneth!",
            createdAt: "5h ago",
            upvoteCount: 9,
          },
          {
            id: "c-53",
            postId: "post-5",
            parentId: "c-51",
            author: {
              id: "usr-cebu3",
              name: "Janine Lim",
              username: "janine_l",
              avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
              badge: "Frequent Traveler",
              reputationPoints: 340,
              verifiedAnswersCount: 4,
            },
            body: "Take note lang na past 9 PM medyo bihira na ang MyBus sa airport so Grab or Taxi na ang best option.",
            createdAt: "3h ago",
            upvoteCount: 5,
          },
        ],
      },
      {
        id: "c-54",
        postId: "post-5",
        author: {
          id: "usr-cebu4",
          name: "Marco Flores",
          username: "marco_f",
          avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
          badge: "Cebu Resident",
          reputationPoints: 890,
          verifiedAnswersCount: 14,
        },
        body: "Kung may Beep card ka, magagamit mo rin sa MyBus. Safe din biyahe kahit mag-isa!",
        createdAt: "2h ago",
        upvoteCount: 4,
      },
    ],
  },
  {
    id: "post-6",
    author: {
      id: "usr-6",
      name: "Bea Alcantara",
      username: "bea_baguio",
      avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
      badge: "Baguio Local",
      reputationPoints: 1640,
      verifiedAnswersCount: 38,
    },
    title: "Saan ang terminal ng jeep papuntang Camp John Hay mula Baguio Gov Pack?",
    origin: "Baguio Bus Terminal (Gov Pack)",
    destination: "Camp John Hay (TechnoHub)",
    body: "Saan po ang TODA terminal ng jeep papuntang Camp John Hay mula Gov Pack? May toda rin ba ng tricycle sa Baguio o taxi/jeep lang talaga?",
    region: "Baguio",
    transportModes: ["Jeepney", "Walk"],
    answerCount: 2,
    upvoteCount: 22,
    bookmarkCount: 0,
    userVoteState: null,
    isBookmarked: false,
    status: "answered",
    createdAt: "12h ago",
    comments: [
      {
        id: "c-61",
        postId: "post-6",
        author: {
          id: "usr-6-reply",
          name: "Bea Alcantara",
          username: "bea_baguio",
          avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
          badge: "Baguio Local",
          reputationPoints: 1640,
          verifiedAnswersCount: 38,
        },
        body: "Mula Gov Pack road, lakad ka lang papuntang Upper Session Road terminal sa tapat ng SM Baguio. May Plaza-Camp John Hay jeep TODA terminal doon (₱15 fare). Pwede ring mag-taxi around ₱80-₱100 lang.",
        createdAt: "10h ago",
        upvoteCount: 12,
        isVerified: true,
      },
      {
        id: "c-62",
        postId: "post-6",
        author: {
          id: "usr-baguio-2",
          name: "Rene Garcia",
          username: "rene_baguio",
          avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
          badge: "Commuter",
          reputationPoints: 480,
          verifiedAnswersCount: 9,
        },
        body: "Walang tricycle sa Baguio City main areas, taxi at jeep lang talaga!",
        createdAt: "8h ago",
        upvoteCount: 8,
      },
    ],
  },
  {
    id: "post-7",
    author: {
      id: "usr-7",
      name: "Mark Villanueva",
      username: "markv_ph",
      avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
      badge: "Commuter",
      reputationPoints: 310,
      verifiedAnswersCount: 5,
    },
    title: "Pinakamabilis na commute route mula Antipolo Cathedral papuntang Market! Market! Taguig?",
    origin: "Antipolo Cathedral",
    destination: "Market! Market! Taguig",
    body: "Ano po pinakamabilis na commute route mula Antipolo simbahan papunta Market Market Taguig? UV Express ba pabalik Ayala o LRT-2 Antipolo to Cubao MRT?",
    region: "Metro Manila",
    transportModes: ["UV Express", "LRT-2", "MRT-3"],
    answerCount: 6,
    upvoteCount: 31,
    bookmarkCount: 4,
    userVoteState: "up",
    isBookmarked: false,
    status: "verified",
    createdAt: "30min ago",
    comments: [
      {
        id: "c-71",
        postId: "post-7",
        author: {
          id: "usr-jojo",
          name: "Jojo Mendoza",
          username: "jojo_m",
          avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
          badge: "Antipolo Transit Guide",
          reputationPoints: 1420,
          verifiedAnswersCount: 35,
        },
        body: "Nasa tabi ng Farmers Market terminal (likod ng MRT Cubao station) yung UV Express biyaheng Antipolo Simbahan (₱70). Mabilis lang pag weekend around 40 mins. Baba ka mismo sa simbahan!",
        createdAt: "1d ago",
        upvoteCount: 19,
        isVerified: true,
      },
      {
        id: "c-72",
        postId: "post-7",
        author: {
          id: "usr-72",
          name: "Grace Sy",
          username: "grace_s",
          avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
          badge: "Commuter",
          reputationPoints: 210,
          verifiedAnswersCount: 3,
        },
        body: "Pwede rin sumakay ng UV Express papuntang Ayala/BGC direct mula Antipolo Shopwise terminal!",
        createdAt: "18h ago",
        upvoteCount: 7,
      },
    ],
  },
  {
    id: "post-8",
    author: {
      id: "usr-8",
      name: "Luzviminda Cruz",
      username: "luz_cruz",
      avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
      badge: "Davao Route Scout",
      reputationPoints: 1280,
      verifiedAnswersCount: 31,
    },
    title: "Anong jeep ang sasakyan mula Davao Airport papuntang SM City Ecoland?",
    origin: "Davao Airport (DIA)",
    destination: "SM City Davao (Ecoland)",
    body: "Unang beses sa Davao City! May Davao Bus Rapid Transit na ba o ano pong jeep ang sasakyan mula airport papuntang Ecoland terminal?",
    region: "Davao",
    transportModes: ["Jeepney", "Bus"],
    answerCount: 3,
    upvoteCount: 27,
    userVoteState: null,
    isBookmarked: false,
    status: "verified",
    createdAt: "1d ago",
  },
];

export const MOCK_TRENDING_ROUTES: TrendingRoute[] = [
  { id: "tr-1", origin: "SM North EDSA", destination: "BGC High Street", questionCount: 142, region: "Metro Manila" },
  { id: "tr-2", origin: "Cubao Aurora", destination: "UP Diliman Campus", questionCount: 98, region: "Metro Manila" },
  { id: "tr-3", origin: "Alabang South Station", destination: "Ayala Triangle Makati", questionCount: 84, region: "Metro Manila" },
  { id: "tr-4", origin: "Mactan Airport", destination: "Cebu IT Park", questionCount: 65, region: "Cebu" },
  { id: "tr-5", origin: "Fairview Market", destination: "Eastwood City Libis", questionCount: 52, region: "Metro Manila" },
];

export const MOCK_UNANSWERED_QUESTIONS: UnansweredQuestion[] = [
  {
    id: "uq-1",
    title: "UST España papuntang PUP Sta. Mesa via jeep o tricycle?",
    origin: "UST España, Manila",
    destination: "PUP Main Campus, Sta. Mesa",
    region: "Metro Manila",
    createdAt: "13m ago",
  },
  {
    id: "uq-2",
    title: "Trinoma papuntang Venice Grand Canal Mall sa McKinley Hill?",
    origin: "Trinoma, Quezon City",
    destination: "McKinley Hill, Taguig",
    region: "Metro Manila",
    createdAt: "17m ago",
  },
  {
    id: "uq-3",
    title: "Saan ang sakayan ng P2P bus mula Katipunan papuntang One Ayala?",
    origin: "Katipunan Avenue",
    destination: "One Ayala, Makati",
    region: "Metro Manila",
    createdAt: "25m ago",
  },
  {
    id: "uq-4",
    title: "Paano mag-commute mula Colon Street papuntang SM Seaside Cebu?",
    origin: "Colon Street, Cebu",
    destination: "SM Seaside City Cebu",
    region: "Cebu",
    createdAt: "42m ago",
  },
];

export const MOCK_TOP_CONTRIBUTORS: TopContributor[] = [
  {
    id: "tc-1",
    rank: 1,
    user: {
      id: "usr-1",
      name: "Carlo Mendoza",
      username: "carlom",
      avatarUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
      badge: "Route Master",
      reputationPoints: 3420,
      verifiedAnswersCount: 89,
    },
  },
  {
    id: "tc-2",
    rank: 2,
    user: {
      id: "usr-5",
      name: "Kenneth Tan",
      username: "ken_tan",
      avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
      badge: "Cebu Specialist",
      reputationPoints: 2150,
      verifiedAnswersCount: 65,
    },
  },
  {
    id: "tc-3",
    rank: 3,
    user: {
      id: "usr-2",
      name: "Maria Santos",
      username: "mariacommutes",
      avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      badge: "LRT Veteran",
      reputationPoints: 1890,
      verifiedAnswersCount: 42,
    },
  },
  {
    id: "tc-4",
    rank: 4,
    user: {
      id: "usr-6",
      name: "Bea Alcantara",
      username: "bea_baguio",
      avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
      badge: "Baguio Local",
      reputationPoints: 1640,
      verifiedAnswersCount: 38,
    },
  },
];

export const MOCK_COMMUNITY_STATS: CommunityStat[] = [
  { id: "cs-1", label: "Verified Answers", value: "4,820+", change: "+120 nitong linggo" },
  { id: "cs-2", label: "Active Commuters", value: "18.5k", change: "Sa buong Pilipinas" },
  { id: "cs-3", label: "Mapped Routes", value: "1,240", change: "Jeep, UV, LRT, TODA" },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [];
